
# This include defination of modbus TCP/IP spec
# Function codes we will use read holding register for bss


# Default Port modbus
MODBUS_DEFAULT_PORT = 502
MODBUS_DEFAULT_SLAVE_ADRESS = 0x01 # Default slave address for plc tested it
MODBUS_TCP = 1

# Function codes
MODBUS_READ_COILS = 0x01 # Read coils as logic
MODBUS_READ_DISCRETE_INPUTS = 0x02
MODBUS_READ_HOLDING_REGISTERS = 0x03 # Read holding registers
MODBUS_READ_INPUT_REGISTERS = 0x04
MODBUS_WRITE_SINGLE_COIL = 0x05
MODBUS_WRITE_SINGLE_REGISTER = 0x06
MODBUS_WRITE_MULTIPLE_COILS = 0x0F
MODBUS_WRITE_MULTIPLE_REGISTERS = 0x10
MODBUS_ENCAPSULATED_INTERFACE = 0x2B

# Module error codes
MB_NO_ERR = 0
MB_RESOLVE_ERR = 1
MB_CONNECT_ERR = 2
MB_SEND_ERR = 3
MB_RECV_ERR = 4
MB_TIMEOUT_ERR = 5
MB_FRAME_ERR = 6
MB_EXCEPT_ERR = 7
MB_CRC_ERR = 8 # for serial
